apiVersion: v1
kind: ConfigMap
metadata:
  name: systeam-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0"
  SPRING_DATASOURCE_USERNAME: "postgres.enweqjzmmgxhbsglwbbz"
  BLOCKCHAIN_RPC_URL: "https://sepolia.base.org/"
  BLOCKCHAIN_CHAIN_ID: "84532"
  BLOCKCHAIN_PAYMENT_GATEWAY: "0x7aabb2435e3220c4bd51cc6546e6899fe75a3f10"
  BLOCKCHAIN_PROJECT_TOKEN: "0x04323eC5d192012c29A5D6A1F120489C03033eD7"
  BLOCKCHAIN_USDC: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
  BLOCKCHAIN_TREASURY: "0x7eEA865D2f47B5cC0fF4c8967C1cCf667fEBE50A"
  BLOCKCHAIN_TOKEN_FACTORY: "0x23a81e62f190993c932ccea79308f8ff1ea558d9"
  BLOCKCHAIN_INVESTMENT_SWAP: "0xdFEf6eF8d9208143D4bFfdfae970fC6DD1Ba0297"
  BLOCKCHAIN_IDEAFY_FACTORY: "0x996b8D9f5e6F1a8AF7dE381D1d703F8E2355bc06"
  BLOCKCHAIN_OFFERING_CONTRACT: "0xfDa7ff1D7C9AEF92982753C1dE0A4F375BAecc43"
  BLOCKCHAIN_IDEA_TOKEN: "0x04323eC5d192012c29A5D6A1F120489C03033eD7"
  BLOCKCHAIN_IDEA_SWAP: "0x23A81e62f190993c932ccEA79308F8fF1ea558d9"
  BLOCKCHAIN_IDEA_MARKETPLACE: "0x9F2C766D0bd9BBB640422dECDf0125Be02C7D144"
  BLOCKCHAIN_IDEA_GOVERNANCE: "0x0BeD59e0201D96b74c8D51A306425be4c81Cf9C6"
  BLOCKCHAIN_DIVIDEND_DISTRIBUTOR: "0xE1056126924568D677669C736A90B2Ae588b0091"
  BLOCKCHAIN_ORACLE_BILLING: "0xC6A9e72f348e946d66589d7AD74c30d876c59E42"
  APP_SECURITY_JWT_EXPIRATION_MS: "3600000"
  GOOGLE_CLIENT_ID: "889190443263-ugcdadkkgu030ush9se98f98koat3ace.apps.googleusercontent.com"
  VITE_WC_PROJECT_ID: "e234b690ba2bac04cd2db93280f289a3"
  VITE_IDEA_TOKEN_ADDRESS: "0x04323eC5d192012c29A5D6A1F120489C03033eD7"
  VITE_INVESTMENT_SWAP_ADDRESS: "0xdFEf6eF8d9208143D4bFfdfae970fC6DD1Ba0297"
  VITE_USDC_ADDRESS: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: systeam-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: systeam-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: SPRING_DATASOURCE_PASSWORD
    - secretKey: BLOCKCHAIN_PRIVATE_KEY
      remoteRef:
        key: BLOCKCHAIN_PRIVATE_KEY
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: JWT_PRIVATE_KEY
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: JWT_PUBLIC_KEY
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: GOOGLE_CLIENT_SECRET
