apiVersion: v1
kind: ConfigMap
metadata:
  name: systeam-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0"
  SPRING_DATASOURCE_USERNAME: "postgres.enweqjzmmgxhbsglwbbz"
  BLOCKCHAIN_RPC_URL: "https://sepolia.base.org/"
  BLOCKCHAIN_CHAIN_ID: "84532"
  BLOCKCHAIN_PAYMENT_GATEWAY: "0x7aabb2435e3220c4bd51cc6546e6899fe75a3f10"
  BLOCKCHAIN_PROJECT_TOKEN: "0x9f2c766d0bd9bbb640422decdf0125be02c7d144"
  BLOCKCHAIN_USDC: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
  BLOCKCHAIN_TREASURY: "0x7eEA865D2f47B5cC0fF4c8967C1cCf667fEBE50A"
  BLOCKCHAIN_TOKEN_FACTORY: "0x23a81e62f190993c932ccea79308f8ff1ea558d9"
  BLOCKCHAIN_INVESTMENT_SWAP: "0xE39F0a7f58d412fa7217607fD3a21713f8e4E232"
  BLOCKCHAIN_IDEAFY_FACTORY: "0x462051fdda4eF66d00F2BbF4fE530570BF3Fd57A"
  BLOCKCHAIN_OFFERING_CONTRACT: "0xE39F0a7f58d412fa7217607fD3a21713f8e4E232"
  BLOCKCHAIN_IDEA_TOKEN: "0x25e6aebd5cb2b9724c5aecC8E8c67fBe5326D409"
  BLOCKCHAIN_IDEA_SWAP: "0xca68b57E7660668EEca658909CEdc5f3a32144a4"
  BLOCKCHAIN_IDEA_MARKETPLACE: "0x5A63e3E2b6675058e4943810DD5aFE8de144Ec43"
  BLOCKCHAIN_IDEA_GOVERNANCE: "0x7F6b4E4741A7C4f844180f0d59E5cc982b389b43"
  BLOCKCHAIN_DIVIDEND_DISTRIBUTOR: "0xa90Ee28790DfFE146083DC10Ae79C96E66927c9F"
  BLOCKCHAIN_ORACLE_BILLING: "0x000e5231e622280b97163ee8e1AaC8Af70B327B5"
  APP_SECURITY_JWT_EXPIRATION_MS: "3600000"
  GOOGLE_CLIENT_ID: "889190443263-ugcdadkkgu030ush9se98f98koat3ace.apps.googleusercontent.com"
  VITE_WC_PROJECT_ID: "e234b690ba2bac04cd2db93280f289a3"
  VITE_IDEA_TOKEN_ADDRESS: "0x25e6aebd5cb2b9724c5aecC8E8c67fBe5326D409"
  VITE_INVESTMENT_SWAP_ADDRESS: "0xE39F0a7f58d412fa7217607fD3a21713f8e4E232"
  VITE_USDC_ADDRESS: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: systeam-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: systeam-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: SPRING_DATASOURCE_PASSWORD
    - secretKey: BLOCKCHAIN_PRIVATE_KEY
      remoteRef:
        key: BLOCKCHAIN_PRIVATE_KEY
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: JWT_PRIVATE_KEY
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: JWT_PUBLIC_KEY
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: GOOGLE_CLIENT_SECRET
