apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
    chart: external-secrets
    helm:
      parameters:
        - name: serviceAccount.annotations.iam\.gke\.io/gcp-service-account
          value: "external-secrets-sa@project-1944cf83-7f15-4f33-89b.iam.gserviceaccount.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
