apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: systeam-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ideafy.lat
      secretName: systeam-tls
  rules:
    - host: ideafy.lat
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /oauth2/authorization
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
