apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    gcpsm:
      projectID: project-1944cf83-7f15-4f33-89b
